version: '3.4'

services:
  backend:
    image: app-backend:1.00
    build: ./backend
    container_name: fastapi-backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://hello_fastapi:hello_fastapi@db:5432/hello_fastapi_dev}
      - SECRET_KEY=
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/dist
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    command: gunicorn --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker src.main:app
    # only allow local, forbid other outside access through port 8000
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db

# no need frontend in Prod. server
  # frontend:
  #   image: app-frontend:1.00

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=hello_fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:  
