version: '3.4'

services:
  backend:
    image: app-backend-debug:1.00
    build: ./backend
    container_name: fastapi-backend-debug
    environment:
      - DATABASE_URL=postgres://hello_fastapi:hello_fastapi@db:5432/hello_fastapi_dev
      - SECRET_KEY=changethis
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/dist
    command: sh -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db

  frontend:
    image: app-frontend:1.00
    build: ./frontend
    container_name: vue-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080  # 8200:8080 publish port 8080 (inside container) as 8200 on host

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 54320:5432

volumes:
  postgres_data:  
